name: Docs to PDF

on:
  workflow_dispatch:

jobs:
  find_markdown_files:
    name: Find Markdown Files
    runs-on: ubuntu-latest
    outputs:
      markdown_files: ${{ steps.find_files.outputs.markdown_files }}
    steps:
      - uses: actions/checkout@v3

      - name: Find Markdown files
        id: find_files
        run: |
          # 查找所有 Day 开头目录下的 .md 文件
          files=($(find . -maxdepth 2 -type f -name "*.md" -path "./Day*"))
          # 构建不带 './' 前缀的 JSON 数组字符串
          output="["
          for file in "${files[@]}"; do
            # Remove "./" prefix
            file=${file#./}
            # Escape double quotes within the filename (if any)
            file=${file//\"/\\\"}
            output+="\"${file}\","
          done
          output="${output%,}"  # Remove trailing comma
          output+="]"
          echo "markdown_files=$output" >> $GITHUB_OUTPUT
          echo "::set-output name=markdown_files::$output"  # 设置输出变量

  converttopdf:
    name: Build PDF for ${{ matrix.file }}
    needs: find_markdown_files  # 依赖于 find_markdown_files job
    runs-on: ubuntu-latest
    strategy:
      matrix:
        file: ${{ fromJson(needs.find_markdown_files.outputs.markdown_files) }} # 从 find_markdown_files job 的输出读取文件列表，并转换为 JSON 数组
    steps:
      - uses: actions/checkout@v3

      - name: Convert to PDF
        uses: baileyjm02/markdown-to-pdf@v1
        with:
          input_file: ${{ matrix.file }}        #  md 文件路径
          output_dir: pdfs # PDF 输出到 pdfs 目录
          # images_dir: ${{ matrix.directory }}/res/day  #  不再需要目录
          image_import: ./res/day         # Markdown 文件中图片引用路径不变
          build_html: false

      - uses: actions/upload-artifact@v3
        with:
          name: docs
          path: pdfs
