name: Docs to PDF

on:
  workflow_dispatch:

jobs:
  converttopdf:
    name: Build PDF for ${{ matrix.directory }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        directory: ${{ steps.find_dirs.outputs.directories }} # 从步骤输出读取目录列表
    steps:
      - uses: actions/checkout@v3

      - name: Find directories
        id: find_dirs
        run: |
          # 查找根目录下所有以 Day 开头，并包含数字的目录
          dirs=$(find . -maxdepth 1 -type d -name "Day*" | jq -R -s 'split("\n")[:-1]') # 提取目录列表并转换成 JSON 数组
          echo "directories=$dirs" >> $GITHUB_OUTPUT
          echo "::set-output name=directories::$dirs"  # 设置输出变量

      - name: Convert to PDF
        uses: baileyjm02/markdown-to-pdf@v1
        with:
          input_dir: ${{ matrix.directory }}        # 直接使用根目录下的目录名
          output_dir: pdfs/${{ matrix.directory }} # PDF 输出到 pdfs/DayXX-YY 目录
          images_dir: ${{ matrix.directory }}/res/day # 图片目录在 DayXX-YY/res/day
          image_import: ./res/day           # Markdown 文件中图片引用路径不变
          build_html: false

      - uses: actions/upload-artifact@v3
        with:
          name: docs
          path: pdfs
