name: Docs to Single PDF

on:
  workflow_dispatch:

jobs:
  find_markdown_files:
    name: Find Markdown Files
    runs-on: ubuntu-latest
    outputs:
      markdown_files: ${{ steps.find_files.outputs.markdown_files }}
    steps:
      - uses: actions/checkout@v3

      - name: Find Markdown files
        id: find_files
        run: |
          # 查找所有 Day 开头目录下的 .md 文件, 按照目录名->文件夹名->文件名排序
          find_output=$(find . -maxdepth 2 -type f -name "*.md" -path="./Day*/res" | sort)
          files=($find_output)

          # 构建不带 './' 前缀的 JSON 数组字符串
          output="["
          for file in "${files[@]}"; do
            # Remove "./" prefix
            file=${file#./}
            # Escape double quotes within the filename (if any)
            file=${file//\"/\\\"}
            output+="\"${file}\","
          done
          output="${output%,}"  # Remove trailing comma
          output+="]"
          echo "markdown_files=$output" >> $GITHUB_OUTPUT
          echo "::set-output name=markdown_files::$output"  # 设置输出变量

  convert_to_single_pdf:
    name: Convert to Single PDF
    needs: find_markdown_files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Pandoc
        run: |
          sudo apt-get update
          sudo apt-get install pandoc
          sudo apt-get install texlive-xetex # Required for PDF generation with Chinese characters and correct font handling
          sudo apt-get install texlive-latex-extra  # Install additional LaTeX packages
          sudo apt-get install fonts-wqy-zenhei # Install WenQuanYi Zen Hei font
          sudo apt-get install python3 python3-pip # Install Python

          # 获取默认模板并保存到 custom.tex
          pandoc -D latex > custom.tex

          # 使用Python脚本修改 custom.tex
          python3 modify_latex.py

      - name: Install pandoc-crossref
        run: |
          ARCH=$(uname -m)
          if [[ "$ARCH" == "x86_64" ]]; then
            ARCH="amd64"
          fi
          PANDOC_CROSSREF_VERSION="0.3.16.0a" # 替换为最新的版本号
          # wget https://github.com/lierdakil/pandoc-crossref/releases/download/v${PANDOC_CROSSREF_VERSION}/pandoc-crossref-linux-$ARCH.tar.gz
          wget https://github.com/lierdakil/pandoc-crossref/releases/download/v${PANDOC_CROSSREF_VERSION}/pandoc-crossref-Linux.tar.xz
          tar -xf pandoc-crossref-Linux.tar.xz
          sudo mv pandoc-crossref /usr/local/bin/
          chmod +x /usr/local/bin/pandoc-crossref
          pandoc-crossref --version # Verify installation

      - name: Create Symlink for Images & Merge Markdown Files
        id: merge_files
        run: |
          # Create a symlink to a common image directory
          mkdir -p all_images

          find . -maxdepth 3 -type d -name "res" -path "./Day*/res" -print0 | while IFS= read -r -d $'\0' res_dir; do
            day_dir=$(dirname "$res_dir") # 获取 Day** 目录
            day_name=$(basename "$day_dir")  # 获取 Day**

            # 处理 Day**/res/day 路径
            day_res_day_dir="$res_dir/day"
            if [ -d "$day_res_day_dir" ]; then
              ln -s "$day_res_day_dir" "all_images/${day_name}_day"
            fi

            # 处理 Day**/res 路径 (将 Day**_res 格式用于此路径)
            ln -s "$res_dir" "all_images/${day_name}_res"

          done

          #markdown_files=$(echo '${{ needs.find_markdown_files.outputs.markdown_files }}' | jq -r '.[]' | tr '\n' ' ')
          #echo "Markdown files to merge: $markdown_files"

          # Pandoc 命令，添加书签功能
          pandoc --toc \
                 --toc-depth=2 \
                 --metadata title="Combined Documentation" \
                 --resource-path="./all_images" \
                 --pdf-engine=xelatex \
                 --from markdown+raw_html \
                 --filter pandoc-crossref \
                 --variable mainfont="WenQuanYi Zen Hei" \
                 --template custom.tex \
                 --output combined.pdf Day01-20/01.初识Python.md

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ordered-docs
          path: combined.pdf
