name: Docs to Single PDF

on:
  workflow_dispatch:

jobs:
  find_markdown_files:
    name: Find Markdown Files
    runs-on: ubuntu-latest
    outputs:
      markdown_files: ${{ steps.find_files.outputs.markdown_files }}
    steps:
      - uses: actions/checkout@v3

      - name: Find Markdown files
        id: find_files
        run: |
          # 查找所有 Day 开头目录下的 .md 文件, 按照目录名->文件夹名->文件名排序
          find_output=$(find . -maxdepth 2 -type f -name "*.md" -path "./Day*" | sort)
          files=($find_output)

          # 构建不带 './' 前缀的 JSON 数组字符串
          output="["
          for file in "${files[@]}"; do
            # Remove "./" prefix
            file=${file#./}
            # Escape double quotes within the filename (if any)
            file=${file//\"/\\\"}
            output+="\"${file}\","
          done
          output="${output%,}"  # Remove trailing comma
          output+="]"
          echo "markdown_files=$output" >> $GITHUB_OUTPUT
          echo "::set-output name=markdown_files::$output"  # 设置输出变量

  convert_to_single_pdf:
    name: Convert to Single PDF
    needs: find_markdown_files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Pandoc
        run: |
          sudo apt-get update
          sudo apt-get install pandoc

      - name: Merge Markdown Files
        id: merge_files
        run: |
          markdown_files=$(echo '${{ needs.find_markdown_files.outputs.markdown_files }}' | jq -r '.[]' | tr '\n' ' ')
          echo "Markdown files to merge: $markdown_files"
          pandoc $markdown_files -o combined.md # 使用pandoc命令合并文件

      - name: Convert to PDF
        uses: baileyjm02/markdown-to-pdf@v1
        with:
          input_path: combined.md #将合并后的 Markdown 文件传递给转换器
          output_dir: pdfs
          image_import: ./res/day # Markdown 文件中图片引用路径不变
          build_html: false

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ordered-docs
          path: pdfs
